### PR TITLE
ci

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 08e9670 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 08e9670e07a8e0634d34f1986fac9d0e58bb1563 with merge 01080b0b78c48e0ff55717b434435fa7958c15ea...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/mfrc522/builds/309447608?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 01080b0b78c48e0ff55717b434435fa7958c15ea to master...

**Pull request merged**
