### PR TITLE
Raspberry Pi support

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b9e1426 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b9e14260d73e5e000dc6b73a813fbac3b9801a06 with merge 296d0af8b26a32a19a5ba6ccdaa5c52071069160...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/mfrc522/builds/309787373?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 296d0af8b26a32a19a5ba6ccdaa5c52071069160 to master...

**Pull request merged**
